default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: brapps-api_development

test:
  <<: *default
  database: brapps-api_test

production:
  <<: *default
  database: brapps-api_production
  username: brapps-api
  password: <%= ENV['BRAPPS-API_DATABASE_PASSWORD'] %>
